environment:
  matrix:
    - PYTHON: "C:\\PYTHON38-x64"
build: off
install:
  - set PATH=C:\msys64\usr\bin;%PATH%
  # Download and unpack zstd for win64 to unpack MSYS packages
  - appveyor DownloadFile https://github.com/facebook/zstd/releases/download/v1.5.5/zstd-v1.5.5-win64.zip
  - 7z e zstd-v1.5.5-win64.zip -ozstd -y
  # Load PGP Keys for Msys64
  - appveyor DownloadFile https://repo.msys2.org/msys/x86_64/msys2-keyring-1~20230316-1-any.pkg.tar.zst
  - appveyor DownloadFile https://repo.msys2.org/msys/x86_64/msys2-keyring-1~20230316-1-any.pkg.tar.zst.sig
  - dir
  - zstd\zstd.exe -d msys2-keyring-1~20230316-1-any.pkg.tar.zst
  - bash -lc "cd /c/projects/python-tksvg; ls -l
  # Verify signature AFTER updating the keyring because MSYS messes with keys too much
  - bash -lc "cd /c/projects/python-tksvg; ls -l
  # Kill gpg-agent due to bug in MSYS
  - START /wait taskkill /f /im gpg-agent.exe
  # Download and install zstd for MSYS due to bug in MSYS
  - appveyor DownloadFile https://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-zstd-1.5.5-1-any.pkg.tar.zst
  - zstd\zstd.exe -d mingw-w64-x86_64-zstd-1.5.5-1-any.pkg.tar.zst
  - dir
  - 7z a -tgzip mingw-w64-x86_64-zstd-1.5.5-1-any.pkg.tar.gz mingw-w64-x86_64-zstd-1.5.5-1-any.pkg.tar
  - bash -lc "cd /c/projects/python-tksvg; ls -l
  # Install Python build dependencies
  - "%PYTHON%\\python.exe -m pip install scikit-build nose"
  # Now using MinGW pkg-config and related executables
  - set PATH=C:\msys64\mingw64\bin;%PATH%
  # Download Dependencies (dependency walker)
  - appveyor DownloadFile https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x64_Release.zip
  - 7z e Dependencies_x64_Release.zip -odeps -y
  # Add %PYTHON% to the path for libffi-7.dll
  - set PATH=%PYTHON%;C:\msys64\mingw64\lib;%PATH%
  - "%PYTHON%\\python.exe -m pip install -U pip setuptools wheel"
build_script:
  - "%PYTHON%\\python.exe setup.py build bdist_wheel --plat-name win_amd64"
  # Simplify PATH so as to test binary distribution
  - set PATH=C:\WINDOWS\system32;C:\WINDOWS
test_script:
  - "%PYTHON%\\python.exe -m nose"
artifacts:
  - path: "/dist/*.whl"
deploy:
  provider: GitHub
  auth_token:
    secure: w1pwzVAnkw938lSYuIKnVbkHtid9YphEEZuHsvftTV5f5KjBAQH3283q7Um5j3xU
  artifact: /.*\.whl/
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
